### PR TITLE
added standard resolution types

### PR DESCRIPTION
**Pull request by mhdzumair**

### CODE REVIEW

**Comment by mhdzumair** [comment]
@platelminto tests are passed. Only issue is unable to detect `QHD` due to ignore case in, `matches = list(re.finditer(pattern, clean_name, re.IGNORECASE))`  instead it's identified as `qHD` which is 540p.

Do you know any other way to distinguish, identify both? If not, It's fine for me to have other standard resolutions types.

**Comment by mhdzumair** [comment]
For example torrent title:  

`www.1TamilBlasters.lat - Thuritham (2023) [Tamil - 2K QHD AVC UNTOUCHED - x264 - AAC - 3.4GB - ESub].mkv` 

this need to be like `1440p`

**Comment by dreulavelle** [comment]
I'm also waiting for this PR too

**Comment by platelminto** [comment]
Should now be available in 2.8.1! I've opened an issue for `qHD` case-sensitivity, so for now it defaults to `QHD`. Thank you for opening this PR!

(Sorry if I screwed up the commits and stuff, if you can next time make a PR into `dev`, not `master`!)

**Comment by mhdzumair** [comment]
No worries. I forgot to change the target branch.

**Pull request closed without merging**
