### PR TITLE
Support for site with title, season, episode, shorten lang names & etc regex patterns

### LINKED ISSUE #51: Website before rest of torrent name is included in title
Examples:

- `Crazy4TV.com - Dark Matter Season 1 S01 720p BluRay x265 HEVC Crazy4ad`
- `www.Torrenting.com - Presque.2021.FRENCH.1080p.WEB.H264-SEiGHT`

Expected behaviour:

- `Crazy4TV.com` & `www.Torrenting.com` should be in `website`, and `title` should just be `Dark Matter` & `Presque`.

### PR DESCRIPTION
**Pull request by mhdzumair**
## Changes
- Capturing the site url in front of title. 
- Add regex for capturing more season patterns
- Add regex for capturing multi episodes with season
- Add few shorten language names
- Add few patterns for missing resolution & quality types

close #51

### CODE REVIEW

**Comment by platelminto** [comment]
Hey, thanks for opening this!

Could you include some test torrent titles for each of these changes? Examples that would've failed before this PR, and are fixed by it.

You can do so by appending the original torrent title to `tests/files/input.json`, the raw output (i.e. using `PTN.parse("torrent_title", standardise=False`) to `tests/files/output_raw.json`, and the standardised output (i.e. the default one) to `tests/files/output_standardised.json`. In this latter one, only include `title` and any fields that are different from the raw version. See [Contributing](https://github.com/platelminto/parse-torrent-title/tree/master#contributing) for more info.

**Comment by mhdzumair** [comment]
Sure ill add those.

**Comment by mhdzumair** [comment]
@platelminto please review the changes. I have pulled your changes from dev branch as well as change this PR to dev.

**Review by platelminto — APPROVED** [review]

**Comment by platelminto** [comment]
Hey, thanks for a great PR!

Good changes, I've looked at the code they changed and simplified/made them more specific where needed. I will merge this PR as-is, then include what I've changed (there's definitely a better way of doing this in GitHub but alas).

Thanks a lot for your help!

**Pull request merged**
